const mongoose = require('mongoose')

const TodoSchema = new mongoose.Schema({
  todo: {
    type: String,
    required: true,
  },
  completed: {
    type: Boolean,
    required: true,
  },
  userId: {
    type: String,
    required: true
  },
  title: {
    type: String,
    required: true
  },
  date:{
      type: String,
      default: `${new Date().toDateString()} ${new Date().toTimeString()}`
  }},
  {
    timestamps: true 
  }
  // updatedAt is autogenerated, same as createdAt, until next PUT req modifies
  // the `todosController.markIncomplete` is modified so that updatedAt does not change when items are marked INcomplete.
  // https://mongoosejs.com/docs/timestamps.html
  // should we prevent >1 click on completed within same minute?
)

module.exports = mongoose.model('Todo', TodoSchema)
